package logica;
// default package
// Generated 7 oct. 2020 00:43:56 by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Deporte generated by hbm2java
 */
public class Deporte implements java.io.Serializable {

	private String nombreDeporte;
	private Set lugarRealizacions = new HashSet(0);
	private Set competencias = new HashSet(0);

	public Deporte() {
	}

	public Deporte(String nombreDeporte) {
		this.nombreDeporte = nombreDeporte;
	}

	public Deporte(String nombreDeporte, Set lugarRealizacions, Set competencias) {
		this.nombreDeporte = nombreDeporte;
		this.lugarRealizacions = lugarRealizacions;
		this.competencias = competencias;
	}

	public String getNombreDeporte() {
		return this.nombreDeporte;
	}

	public void setNombreDeporte(String nombreDeporte) {
		this.nombreDeporte = nombreDeporte;
	}

	public Set getLugarRealizacions() {
		return this.lugarRealizacions;
	}

	public void setLugarRealizacions(Set lugarRealizacions) {
		this.lugarRealizacions = lugarRealizacions;
	}

	public Set getCompetencias() {
		return this.competencias;
	}

	public void setCompetencias(Set competencias) {
		this.competencias = competencias;
	}

}
