package logica;
// default package
// Generated 7 oct. 2020 00:43:56 by Hibernate Tools 5.4.18.Final

/**
 * DisponiblePara generated by hbm2java
 */
public class DisponiblePara implements java.io.Serializable {

	private Competencia competencia;
	private LugarRealizacion lugarRealizacion;
	private Integer cantidadEncuentros;
	public DisponiblePara() {
	}

	public DisponiblePara(Competencia competencia, LugarRealizacion lugarRealizacion,Integer cantidadEncuentros) {
		this.competencia = competencia;
		this.lugarRealizacion = lugarRealizacion;
		this.cantidadEncuentros = cantidadEncuentros;
	}

	public Integer getCantidadEncuentros() {
		return this.cantidadEncuentros;
	}

	public void setCantidadEncuentros(Integer cantidadEncuentros) {
		this.cantidadEncuentros = cantidadEncuentros;
	}

	public Competencia getCompetencia() {
		return this.competencia;
	}

	public void setCompetencia(Competencia competencia) {
		this.competencia = competencia;
	}

	public LugarRealizacion getLugarRealizacion() {
		return this.lugarRealizacion;
	}

	public void setLugarRealizacion(LugarRealizacion lugarRealizacion) {
		this.lugarRealizacion = lugarRealizacion;
	}

}
