package logica;
// default package
// Generated 7 oct. 2020 00:43:56 by Hibernate Tools 5.4.18.Final

/**
 * EliminacionDoble generated by hbm2java
 */
public class EliminacionDoble extends Competencia implements java.io.Serializable {

	public EliminacionDoble() {
		super();
	};
	
}
