package logica;
// default package
// Generated 7 oct. 2020 00:43:56 by Hibernate Tools 5.4.18.Final

/**
 * EliminacionDoble generated by hbm2java
 */
public class EliminacionDoble extends Competencia implements java.io.Serializable {

	public EliminacionDoble() {
		super();
	};
	
	
	public EliminacionDoble(Deporte deporte, String nombre, String estado) {
		super(deporte, nombre, estado);
	}


	public EliminacionDoble(Deporte deporte, FormaPuntuacion forma, Usuario usuario, String nombre, boolean permiteEmpate, String estado) {
		super(deporte, forma, usuario, nombre, permiteEmpate, estado);
	}
}
