package logica;
// default package
// Generated 7 oct. 2020 00:43:56 by Hibernate Tools 5.4.18.Final

/**
 * EliminacionSimple generated by hbm2java
 */
public class EliminacionSimple extends Competencia implements java.io.Serializable {

	public EliminacionSimple() {
		super();
	}

	public EliminacionSimple(Deporte deporte, FormaPuntuacion forma, Usuario usuario, String nombre, boolean permite_empate,
			String estado) {
		super(deporte, forma, usuario, nombre, permite_empate, estado);
	};
	
	
	public EliminacionSimple(Deporte deporte, String nombre, String estado) {
		super(deporte, nombre, estado);
	}
}
