package logica;
// default package
// Generated 7 oct. 2020 00:43:56 by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * FormaPuntuacion generated by hbm2java
 */
public class FormaPuntuacion implements java.io.Serializable {

	private Integer idFormaPuntuacion;
	private Set competencias = new HashSet(0);

	public FormaPuntuacion() {
	}

	public FormaPuntuacion(int idFormaPuntuacion) {
		this.idFormaPuntuacion = idFormaPuntuacion;
	}

	public Integer getIdFormaPuntuacion() {
		return this.idFormaPuntuacion;
	}

	public void setIdFormaPuntuacion(Integer idFormaPuntuacion) {
		this.idFormaPuntuacion = idFormaPuntuacion;
	}

	public Set getCompetencias() {
		return this.competencias;
	}

	public void setCompetencias(Set competencias) {
		this.competencias = competencias;
	}

}
