package logica;
// default package
// Generated 7 oct. 2020 00:43:56 by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * LugarRealizacion generated by hbm2java
 */
public class LugarRealizacion implements java.io.Serializable {

	private Integer idLugar;
	private Usuario usuario;
	private String nombre;
	private Set deportes = new HashSet(0);
	private Set disponibleParas = new HashSet(0);

	public LugarRealizacion() {
	}

	public LugarRealizacion(int idLugar) {
		this.idLugar = idLugar;
	}

	public LugarRealizacion(Integer idLugar, Usuario usuario, String nombre, Set deportes, Set disponibleParas) {
		this.idLugar = idLugar;
		this.usuario = usuario;
		this.nombre = nombre;
		this.deportes = deportes;
		this.disponibleParas = disponibleParas;
	}

	public Integer getIdLugar() {
		return this.idLugar;
	}

	public void setIdLugar(Integer idLugar) {
		this.idLugar = idLugar;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getDeportes() {
		return this.deportes;
	}

	public void setDeportes(Set deportes) {
		this.deportes = deportes;
	}

	public Set getDisponibleParas() {
		return this.disponibleParas;
	}

	public void setDisponibleParas(Set disponibleParas) {
		this.disponibleParas = disponibleParas;
	}

	public void addDeporte(Deporte deporte) {
		// TODO Auto-generated method stub
		deportes.add(deporte);
	}

}
