package logica;
// default package
// Generated 7 oct. 2020 00:43:56 by Hibernate Tools 5.4.18.Final

/**
 * Puntuacion generated by hbm2java
 */
public class Puntuacion extends FormaPuntuacion implements java.io.Serializable {

	private Integer tantosPorDefault;

	public Puntuacion() {
		super();
	}

	public Puntuacion(Integer tantosPorDefault) {
		this.tantosPorDefault = tantosPorDefault;
	}

	public Integer getTantosPorDefault() {
		return this.tantosPorDefault;
	}

	public void setTantosPorDefault(Integer tantosPorDefault) {
		this.tantosPorDefault = tantosPorDefault;
	}

}
