package logica;
// default package
// Generated 7 oct. 2020 00:43:56 by Hibernate Tools 5.4.18.Final

/**
 * ResultadoFinal generated by hbm2java
 */
public class ResultadoFinal extends FormaPuntuacion implements java.io.Serializable {

	public ResultadoFinal() {
		super();
	}

}
