package logica;
// default package
// Generated 7 oct. 2020 00:43:56 by Hibernate Tools 5.4.18.Final

/**
 * Sets generated by hbm2java
 */
public class Sets extends FormaPuntuacion implements java.io.Serializable {

	private Integer cantMaxSets;

	public Sets() {
		super();
	}
	
	public Sets(Integer cantMaxSets) {
		this.cantMaxSets = cantMaxSets;
	}

	public Integer getCantMaxSets() {
		return this.cantMaxSets;
	}

	public void setCantMaxSets(Integer cantMaxSets) {
		this.cantMaxSets = cantMaxSets;
	}

}
