package logica;
// default package
// Generated 7 oct. 2020 00:43:56 by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private Localidad localidad;
	private String nombre;
	private String apellido;
	private String email;
	private String password;
	private Set competencias = new HashSet(0);
	private Set lugarRealizacions = new HashSet(0);

	public Usuario() {
	}

	public Usuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Usuario(Integer idUsuario, Localidad localidad, String nombre, String apellido, String email, String password,
			Set competencias, Set lugarRealizacions) {
		this.idUsuario = idUsuario;
		this.localidad = localidad;
		this.nombre = nombre;
		this.apellido = apellido;
		this.email = email;
		this.password = password;
		this.competencias = competencias;
		this.lugarRealizacions = lugarRealizacions;
	}

	public Usuario(String nombre, String apellido, String email, String password, Localidad localidad) {
		this.localidad = localidad;
		this.nombre = nombre;
		this.apellido = apellido;
		this.email = email;
		this.password = password;
	}
	public Usuario(String nombre, String apellido, String email, String password) {
		//this.localidad = localidad;
		this.nombre = nombre;
		this.apellido = apellido;
		this.email = email;
		this.password = password;
	}
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Localidad getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getCompetencias() {
		return this.competencias;
	}

	public void setCompetencias(Set competencias) {
		this.competencias = competencias;
	}

	public Set getLugarRealizacions() {
		return this.lugarRealizacions;
	}

	public void setLugarRealizacions(Set lugarRealizacions) {
		this.lugarRealizacions = lugarRealizacions;
	}

}
